[package]
name = "contract-interface"
version = "0.1.0"
authors = ["Thiago Machado <thiago@keyko.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0-pre.2"
serde_json = "1.0.0"
near-contract-standards = "4.0.0-pre.2"